package com.zhu8fei.mybatis.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.name
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.real_name
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.email
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.mobile
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.password
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.salt
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.name
     *
     * @return the value of u_user.name
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.name
     *
     * @param name the value for u_user.name
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.real_name
     *
     * @return the value of u_user.real_name
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.real_name
     *
     * @param realName the value for u_user.real_name
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.email
     *
     * @return the value of u_user.email
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.email
     *
     * @param email the value for u_user.email
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.mobile
     *
     * @return the value of u_user.mobile
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.mobile
     *
     * @param mobile the value for u_user.mobile
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.password
     *
     * @return the value of u_user.password
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.password
     *
     * @param password the value for u_user.password
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.salt
     *
     * @return the value of u_user.salt
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.salt
     *
     * @param salt the value for u_user.salt
     *
     * @mbg.generated Tue Mar 28 21:52:47 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}